#!/usr/bin/env python3
"""Insert import-job i18n keys into every values-*/strings.xml."""

from __future__ import annotations

from pathlib import Path

RES = Path(__file__).resolve().parents[1] / "android" / "app" / "src" / "main" / "res"
ANCHOR = '    <string name="import_new_list_option">'

STRINGS: dict[str, dict[str, str]] = {
    "values": {
        "import_section_ready": "Will import (%d)",
        "import_section_duplicates": "Duplicates (%d)",
        "import_section_failed": "Errors (%d)",
        "import_copy_errors": "Copy failed words",
        "import_errors_copied": "Copied %d words",
        "import_reason_already_on_list": "Already on your lists",
        "import_reason_in_file_duplicate": "Repeated in this file",
        "import_reason_no_lemma": "Could not extract a word",
        "import_reason_llm_invalid": "Not recognized",
        "import_reason_write_failed": "Save failed after 3 tries",
        "import_cancelled": "Cancelled. Nothing was added.",
        "import_stage_queued": "Queued…",
        "import_stage_format": "Reading file layout…",
        "import_stage_classify": "Analyzing words…",
        "import_stage_layout": "Laying out cards…",
        "import_stage_dedup": "Checking duplicates",
        "import_stage_write": "Saving to list",
        "import_stage_rollback": "Cancelling and undoing…",
        "import_progress_attempt": "try %1$d/3",
        "import_progress_tally": "OK %1$d · duplicate %2$d · error %3$d",
    },
    "values-en": {},  # copy from values
    "values-pl": {
        "import_section_ready": "Wejdzie (%d)",
        "import_section_duplicates": "Duplikaty (%d)",
        "import_section_failed": "Błędy (%d)",
        "import_copy_errors": "Kopiuj błędne hasła",
        "import_errors_copied": "Skopiowano %d haseł",
        "import_reason_already_on_list": "Już jest na Twoich listach",
        "import_reason_in_file_duplicate": "Powtórzenie w tym pliku",
        "import_reason_no_lemma": "Nie udało się wyciągnąć słowa",
        "import_reason_llm_invalid": "Nie rozpoznano",
        "import_reason_write_failed": "Zapis nie powiódł się (po 3 próbach)",
        "import_cancelled": "Przerwano. Nic nie zostało dodane.",
        "import_stage_queued": "W kolejce…",
        "import_stage_format": "Rozpoznaję układ pliku…",
        "import_stage_classify": "Analizuję słowa…",
        "import_stage_layout": "Układam fiszki…",
        "import_stage_dedup": "Sprawdzam duplikaty",
        "import_stage_write": "Zapisuję na listę",
        "import_stage_rollback": "Anulowanie i cofanie zmian…",
        "import_progress_attempt": "próba %1$d/3",
        "import_progress_tally": "OK %1$d · duplikat %2$d · błąd %3$d",
    },
    "values-es": {
        "import_section_ready": "Se importará (%d)",
        "import_section_duplicates": "Duplicados (%d)",
        "import_section_failed": "Errores (%d)",
        "import_copy_errors": "Copiar palabras con error",
        "import_errors_copied": "Se copiaron %d palabras",
        "import_reason_already_on_list": "Ya está en tus listas",
        "import_reason_in_file_duplicate": "Repetida en este archivo",
        "import_reason_no_lemma": "No se pudo extraer la palabra",
        "import_reason_llm_invalid": "No reconocida",
        "import_reason_write_failed": "Error al guardar (tras 3 intentos)",
        "import_cancelled": "Cancelado. No se añadió nada.",
        "import_stage_queued": "En cola…",
        "import_stage_format": "Leyendo el formato…",
        "import_stage_classify": "Analizando palabras…",
        "import_stage_layout": "Preparando tarjetas…",
        "import_stage_dedup": "Buscando duplicados",
        "import_stage_write": "Guardando en la lista",
        "import_stage_rollback": "Cancelando y deshaciendo…",
        "import_progress_attempt": "intento %1$d/3",
        "import_progress_tally": "OK %1$d · duplicado %2$d · error %3$d",
    },
    "values-fr": {
        "import_section_ready": "Sera importé (%d)",
        "import_section_duplicates": "Doublons (%d)",
        "import_section_failed": "Erreurs (%d)",
        "import_copy_errors": "Copier les mots en erreur",
        "import_errors_copied": "%d mots copiés",
        "import_reason_already_on_list": "Déjà dans tes listes",
        "import_reason_in_file_duplicate": "Répété dans ce fichier",
        "import_reason_no_lemma": "Impossible d’extraire le mot",
        "import_reason_llm_invalid": "Non reconnu",
        "import_reason_write_failed": "Échec de l’enregistrement (après 3 essais)",
        "import_cancelled": "Annulé. Rien n’a été ajouté.",
        "import_stage_queued": "En file…",
        "import_stage_format": "Lecture de la mise en page…",
        "import_stage_classify": "Analyse des mots…",
        "import_stage_layout": "Préparation des cartes…",
        "import_stage_dedup": "Vérification des doublons",
        "import_stage_write": "Enregistrement dans la liste",
        "import_stage_rollback": "Annulation et retour arrière…",
        "import_progress_attempt": "essai %1$d/3",
        "import_progress_tally": "OK %1$d · doublon %2$d · erreur %3$d",
    },
    "values-de": {
        "import_section_ready": "Wird importiert (%d)",
        "import_section_duplicates": "Duplikate (%d)",
        "import_section_failed": "Fehler (%d)",
        "import_copy_errors": "Fehlerhafte Wörter kopieren",
        "import_errors_copied": "%d Wörter kopiert",
        "import_reason_already_on_list": "Schon auf deinen Listen",
        "import_reason_in_file_duplicate": "In dieser Datei wiederholt",
        "import_reason_no_lemma": "Wort konnte nicht erkannt werden",
        "import_reason_llm_invalid": "Nicht erkannt",
        "import_reason_write_failed": "Speichern fehlgeschlagen (nach 3 Versuchen)",
        "import_cancelled": "Abgebrochen. Nichts wurde hinzugefügt.",
        "import_stage_queued": "In der Warteschlange…",
        "import_stage_format": "Dateilayout wird gelesen…",
        "import_stage_classify": "Wörter werden analysiert…",
        "import_stage_layout": "Karten werden vorbereitet…",
        "import_stage_dedup": "Duplikate werden geprüft",
        "import_stage_write": "Wird auf die Liste gespeichert",
        "import_stage_rollback": "Wird abgebrochen und rückgängig gemacht…",
        "import_progress_attempt": "Versuch %1$d/3",
        "import_progress_tally": "OK %1$d · Duplikat %2$d · Fehler %3$d",
    },
    "values-it": {
        "import_section_ready": "Verrà importato (%d)",
        "import_section_duplicates": "Duplicati (%d)",
        "import_section_failed": "Errori (%d)",
        "import_copy_errors": "Copia le parole con errore",
        "import_errors_copied": "Copiate %d parole",
        "import_reason_already_on_list": "Già presente nelle tue liste",
        "import_reason_in_file_duplicate": "Ripetuta in questo file",
        "import_reason_no_lemma": "Impossibile estrarre la parola",
        "import_reason_llm_invalid": "Non riconosciuta",
        "import_reason_write_failed": "Salvataggio non riuscito (dopo 3 tentativi)",
        "import_cancelled": "Annullato. Non è stato aggiunto nulla.",
        "import_stage_queued": "In coda…",
        "import_stage_format": "Lettura del formato…",
        "import_stage_classify": "Analisi delle parole…",
        "import_stage_layout": "Preparazione delle carte…",
        "import_stage_dedup": "Controllo duplicati",
        "import_stage_write": "Salvataggio nella lista",
        "import_stage_rollback": "Annullamento e ripristino…",
        "import_progress_attempt": "tentativo %1$d/3",
        "import_progress_tally": "OK %1$d · duplicato %2$d · errore %3$d",
    },
    "values-pt-rBR": {
        "import_section_ready": "Será importado (%d)",
        "import_section_duplicates": "Duplicatas (%d)",
        "import_section_failed": "Erros (%d)",
        "import_copy_errors": "Copiar palavras com erro",
        "import_errors_copied": "%d palavras copiadas",
        "import_reason_already_on_list": "Já está nas suas listas",
        "import_reason_in_file_duplicate": "Repetida neste arquivo",
        "import_reason_no_lemma": "Não foi possível extrair a palavra",
        "import_reason_llm_invalid": "Não reconhecida",
        "import_reason_write_failed": "Falha ao salvar (após 3 tentativas)",
        "import_cancelled": "Cancelado. Nada foi adicionado.",
        "import_stage_queued": "Na fila…",
        "import_stage_format": "Lendo o formato…",
        "import_stage_classify": "Analisando palavras…",
        "import_stage_layout": "Montando os cards…",
        "import_stage_dedup": "Verificando duplicatas",
        "import_stage_write": "Salvando na lista",
        "import_stage_rollback": "Cancelando e desfazendo…",
        "import_progress_attempt": "tentativa %1$d/3",
        "import_progress_tally": "OK %1$d · duplicata %2$d · erro %3$d",
    },
    "values-pt-rPT": {
        "import_section_ready": "Será importado (%d)",
        "import_section_duplicates": "Duplicados (%d)",
        "import_section_failed": "Erros (%d)",
        "import_copy_errors": "Copiar palavras com erro",
        "import_errors_copied": "%d palavras copiadas",
        "import_reason_already_on_list": "Já está nas tuas listas",
        "import_reason_in_file_duplicate": "Repetida neste ficheiro",
        "import_reason_no_lemma": "Não foi possível extrair a palavra",
        "import_reason_llm_invalid": "Não reconhecida",
        "import_reason_write_failed": "Falha ao guardar (após 3 tentativas)",
        "import_cancelled": "Cancelado. Nada foi adicionado.",
        "import_stage_queued": "Em fila…",
        "import_stage_format": "A ler o formato…",
        "import_stage_classify": "A analisar palavras…",
        "import_stage_layout": "A preparar cartões…",
        "import_stage_dedup": "A verificar duplicados",
        "import_stage_write": "A guardar na lista",
        "import_stage_rollback": "A cancelar e a anular…",
        "import_progress_attempt": "tentativa %1$d/3",
        "import_progress_tally": "OK %1$d · duplicado %2$d · erro %3$d",
    },
    "values-zh": {
        "import_section_ready": "将导入（%d）",
        "import_section_duplicates": "重复（%d）",
        "import_section_failed": "错误（%d）",
        "import_copy_errors": "复制出错的词",
        "import_errors_copied": "已复制 %d 个词",
        "import_reason_already_on_list": "已在你的列表中",
        "import_reason_in_file_duplicate": "此文件中重复",
        "import_reason_no_lemma": "无法提取单词",
        "import_reason_llm_invalid": "无法识别",
        "import_reason_write_failed": "保存失败（已重试 3 次）",
        "import_cancelled": "已取消。没有添加任何内容。",
        "import_stage_queued": "排队中…",
        "import_stage_format": "正在识别文件格式…",
        "import_stage_classify": "正在分析单词…",
        "import_stage_layout": "正在排版卡片…",
        "import_stage_dedup": "正在检查重复",
        "import_stage_write": "正在保存到列表",
        "import_stage_rollback": "正在取消并撤销…",
        "import_progress_attempt": "第 %1$d/3 次尝试",
        "import_progress_tally": "成功 %1$d · 重复 %2$d · 错误 %3$d",
    },
    "values-ja": {
        "import_section_ready": "インポート予定（%d）",
        "import_section_duplicates": "重複（%d）",
        "import_section_failed": "エラー（%d）",
        "import_copy_errors": "エラーの語をコピー",
        "import_errors_copied": "%d語をコピーしました",
        "import_reason_already_on_list": "すでにリストにあります",
        "import_reason_in_file_duplicate": "このファイル内の重複",
        "import_reason_no_lemma": "単語を抽出できませんでした",
        "import_reason_llm_invalid": "認識できませんでした",
        "import_reason_write_failed": "保存に失敗しました（3回試行）",
        "import_cancelled": "中止しました。何も追加されていません。",
        "import_stage_queued": "待機中…",
        "import_stage_format": "ファイル形式を読み取り中…",
        "import_stage_classify": "単語を分析中…",
        "import_stage_layout": "カードを配置中…",
        "import_stage_dedup": "重複を確認中",
        "import_stage_write": "リストに保存中",
        "import_stage_rollback": "中止して元に戻しています…",
        "import_progress_attempt": "試行 %1$d/3",
        "import_progress_tally": "OK %1$d · 重複 %2$d · エラー %3$d",
    },
    "values-ko": {
        "import_section_ready": "가져올 항목 (%d)",
        "import_section_duplicates": "중복 (%d)",
        "import_section_failed": "오류 (%d)",
        "import_copy_errors": "오류 단어 복사",
        "import_errors_copied": "단어 %d개를 복사했습니다",
        "import_reason_already_on_list": "이미 목록에 있습니다",
        "import_reason_in_file_duplicate": "이 파일에서 반복됨",
        "import_reason_no_lemma": "단어를 추출하지 못했습니다",
        "import_reason_llm_invalid": "인식되지 않음",
        "import_reason_write_failed": "저장 실패 (3회 시도)",
        "import_cancelled": "취소됨. 추가된 항목이 없습니다.",
        "import_stage_queued": "대기 중…",
        "import_stage_format": "파일 형식을 읽는 중…",
        "import_stage_classify": "단어를 분석하는 중…",
        "import_stage_layout": "카드를 배치하는 중…",
        "import_stage_dedup": "중복 확인 중",
        "import_stage_write": "목록에 저장 중",
        "import_stage_rollback": "취소하고 되돌리는 중…",
        "import_progress_attempt": "시도 %1$d/3",
        "import_progress_tally": "OK %1$d · 중복 %2$d · 오류 %3$d",
    },
    "values-ar": {
        "import_section_ready": "سيتم الاستيراد (%d)",
        "import_section_duplicates": "مكررات (%d)",
        "import_section_failed": "أخطاء (%d)",
        "import_copy_errors": "نسخ الكلمات الخاطئة",
        "import_errors_copied": "تم نسخ %d كلمة",
        "import_reason_already_on_list": "موجود بالفعل في قوائمك",
        "import_reason_in_file_duplicate": "مكرر في هذا الملف",
        "import_reason_no_lemma": "تعذّر استخراج الكلمة",
        "import_reason_llm_invalid": "غير معروف",
        "import_reason_write_failed": "فشل الحفظ (بعد 3 محاولات)",
        "import_cancelled": "أُلغي. لم يُضف شيء.",
        "import_stage_queued": "في الانتظار…",
        "import_stage_format": "قراءة تخطيط الملف…",
        "import_stage_classify": "تحليل الكلمات…",
        "import_stage_layout": "تجهيز البطاقات…",
        "import_stage_dedup": "التحقق من التكرار",
        "import_stage_write": "الحفظ في القائمة",
        "import_stage_rollback": "إلغاء والتراجع…",
        "import_progress_attempt": "المحاولة %1$d/3",
        "import_progress_tally": "تم %1$d · مكرر %2$d · خطأ %3$d",
    },
    "values-ru": {
        "import_section_ready": "Будет импортировано (%d)",
        "import_section_duplicates": "Дубликаты (%d)",
        "import_section_failed": "Ошибки (%d)",
        "import_copy_errors": "Копировать слова с ошибкой",
        "import_errors_copied": "Скопировано слов: %d",
        "import_reason_already_on_list": "Уже есть в ваших списках",
        "import_reason_in_file_duplicate": "Повтор в этом файле",
        "import_reason_no_lemma": "Не удалось извлечь слово",
        "import_reason_llm_invalid": "Не распознано",
        "import_reason_write_failed": "Не удалось сохранить (после 3 попыток)",
        "import_cancelled": "Отменено. Ничего не добавлено.",
        "import_stage_queued": "В очереди…",
        "import_stage_format": "Читаю формат файла…",
        "import_stage_classify": "Анализирую слова…",
        "import_stage_layout": "Готовлю карточки…",
        "import_stage_dedup": "Проверяю дубликаты",
        "import_stage_write": "Сохраняю в список",
        "import_stage_rollback": "Отмена и откат…",
        "import_progress_attempt": "попытка %1$d/3",
        "import_progress_tally": "OK %1$d · дубликат %2$d · ошибка %3$d",
    },
    "values-hi": {
        "import_section_ready": "आयात होगा (%d)",
        "import_section_duplicates": "डुप्लिकेट (%d)",
        "import_section_failed": "त्रुटियाँ (%d)",
        "import_copy_errors": "गलत शब्द कॉपी करें",
        "import_errors_copied": "%d शब्द कॉपी हुए",
        "import_reason_already_on_list": "पहले से आपकी सूचियों में है",
        "import_reason_in_file_duplicate": "इस फ़ाइल में दोहराया गया",
        "import_reason_no_lemma": "शब्द निकाल नहीं सके",
        "import_reason_llm_invalid": "पहचाना नहीं गया",
        "import_reason_write_failed": "सेव असफल (3 कोशिशों के बाद)",
        "import_cancelled": "रद्द। कुछ नहीं जोड़ा गया।",
        "import_stage_queued": "कतार में…",
        "import_stage_format": "फ़ाइल लेआउट पढ़ रहे हैं…",
        "import_stage_classify": "शब्दों का विश्लेषण…",
        "import_stage_layout": "कार्ड तैयार हो रहे हैं…",
        "import_stage_dedup": "डुप्लिकेट जाँच",
        "import_stage_write": "सूची में सेव हो रहा है",
        "import_stage_rollback": "रद्द करके वापस लिया जा रहा है…",
        "import_progress_attempt": "कोशिश %1$d/3",
        "import_progress_tally": "OK %1$d · डुप्लिकेट %2$d · त्रुटि %3$d",
    },
    "values-tr": {
        "import_section_ready": "İçe aktarılacak (%d)",
        "import_section_duplicates": "Kopyalar (%d)",
        "import_section_failed": "Hatalar (%d)",
        "import_copy_errors": "Hatalı kelimeleri kopyala",
        "import_errors_copied": "%d kelime kopyalandı",
        "import_reason_already_on_list": "Zaten listelerinde var",
        "import_reason_in_file_duplicate": "Bu dosyada tekrarlanmış",
        "import_reason_no_lemma": "Kelime çıkarılamadı",
        "import_reason_llm_invalid": "Tanınmadı",
        "import_reason_write_failed": "Kayıt başarısız (3 denemeden sonra)",
        "import_cancelled": "İptal edildi. Hiçbir şey eklenmedi.",
        "import_stage_queued": "Sırada…",
        "import_stage_format": "Dosya düzeni okunuyor…",
        "import_stage_classify": "Kelimeler analiz ediliyor…",
        "import_stage_layout": "Kartlar hazırlanıyor…",
        "import_stage_dedup": "Kopyalar kontrol ediliyor",
        "import_stage_write": "Listeye kaydediliyor",
        "import_stage_rollback": "İptal edilip geri alınıyor…",
        "import_progress_attempt": "deneme %1$d/3",
        "import_progress_tally": "OK %1$d · kopya %2$d · hata %3$d",
    },
    "values-vi": {
        "import_section_ready": "Sẽ nhập (%d)",
        "import_section_duplicates": "Trùng (%d)",
        "import_section_failed": "Lỗi (%d)",
        "import_copy_errors": "Sao chép từ bị lỗi",
        "import_errors_copied": "Đã sao chép %d từ",
        "import_reason_already_on_list": "Đã có trong danh sách của bạn",
        "import_reason_in_file_duplicate": "Lặp lại trong tệp này",
        "import_reason_no_lemma": "Không trích được từ",
        "import_reason_llm_invalid": "Không nhận diện được",
        "import_reason_write_failed": "Lưu thất bại (sau 3 lần)",
        "import_cancelled": "Đã hủy. Không thêm gì.",
        "import_stage_queued": "Đang chờ…",
        "import_stage_format": "Đang đọc bố cục tệp…",
        "import_stage_classify": "Đang phân tích từ…",
        "import_stage_layout": "Đang xếp thẻ…",
        "import_stage_dedup": "Đang kiểm tra trùng",
        "import_stage_write": "Đang lưu vào danh sách",
        "import_stage_rollback": "Đang hủy và hoàn tác…",
        "import_progress_attempt": "lần %1$d/3",
        "import_progress_tally": "OK %1$d · trùng %2$d · lỗi %3$d",
    },
}


def xml_escape(s: str) -> str:
    return (
        s.replace("&", "&amp;")
        .replace("'", "\\'")
        .replace('"', '\\"')
    )


def block_for(locale: str) -> str:
    data = STRINGS.get(locale) or STRINGS["values"]
    if locale == "values-en":
        data = STRINGS["values"]
    lines = ['    <string name="{k}">{v}</string>'.format(k=k, v=xml_escape(v)) for k, v in data.items()]
    return "\n".join(lines) + "\n\n"


def main() -> None:
    for folder, _ in STRINGS.items():
        path = RES / folder / "strings.xml"
        text = path.read_text(encoding="utf-8")
        if 'name="import_section_ready"' in text:
            print(f"skip {folder}")
            continue
        idx = text.find(ANCHOR)
        if idx < 0:
            raise SystemExit(f"anchor missing in {folder}")
        end = text.find("\n", idx)
        insert_at = end + 1
        text = text[:insert_at] + "\n" + block_for(folder) + text[insert_at:]
        path.write_text(text, encoding="utf-8")
        print(f"ok {folder}")


if __name__ == "__main__":
    main()
